# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mnaschbe <mnaschbe@student.42vienna.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/23 19:05:02 by mnaschbe          #+#    #+#              #
#    Updated: 2023/09/25 13:54:02 by mnaschbe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


# Variables
CNAME = libft.a
CC = gcc 
CFLAGS = -Wall -Wextra -Werror -std=c99
AR = ar -rcs
SRCS = ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
        ft_isdigit.c ft_isprint.c ft_itoa.c ft_memchr.c ft_memcmp.c ft_memcpy.c \
        ft_memmove.c ft_memset.c ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
        ft_putstr_fd.c ft_strchr.c ft_strdup.c ft_striteri.c ft_strjoin.c ft_strlcat.c \
        ft_strlcpy.c ft_strlen.c ft_strmapi.c ft_strncmp.c ft_strnstr.c ft_strrchr.c \
        ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c
OBJS = $(SRCS:.c=.o)

#Execute when run make
all: $(NAME)

$(NAME): $(OBJS) 
    $(AR) $(NAME) $(OBJS)

#Build object files from .c files
%.o: %.c
    $(CC) $(CFLAGS)    -c $< -o $@

#Remove object files
clean:
    rm -f $(OBJS)


#Remove object files and rush-02
fclean: clean
    rm -f $(NAME)

#Rebuild program
re: fclean all

#These targets are always executed
.PHONY: all clean fclean re